apiVersion: 2022-10-01
location: eastus2
type: Microsoft.App/containerApps
properties:
  managedEnvironmentId: /subscriptions/e440a65b-7418-4865-9821-88e411ffdd5b/resourceGroups/edutainmentforge-rg/providers/Microsoft.App/managedEnvironments/edutainmentforge-env
  configuration:
    ingress:
      external: true
      targetPort: 5000
      transport: http
      allowInsecure: false
    secrets:
      - name: azure-speech-key
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/azure-speech-key"
        identity: "system"
      - name: azure-openai-api-key
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/azure-openai-api-key"
        identity: "system"
      - name: azure-openai-endpoint
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/azure-openai-endpoint"
        identity: "system"
      - name: acr-password
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/acr-password"
        identity: "system"
      - name: sarah-voice
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/sarah-voice"
        identity: "system"
      - name: mike-voice
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/mike-voice"
        identity: "system"
      - name: azure-ad-tenant-id
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/azure-ad-tenant-id"
        identity: "system"
      - name: azure-ad-client-id
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/azure-ad-client-id"
        identity: "system"
      - name: azure-ad-client-secret
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/azure-ad-client-secret"
        identity: "system"
      - name: flask-secret-key
        keyVaultUrl: "https://edutainmentforge-kv.vault.azure.net/secrets/flask-secret-key"
        identity: "system"
    registries:
      - server: "edutainmentforge.azurecr.io"
        username: "edutainmentforge"
        passwordSecretRef: "acr-password"
  template:
    containers:
      - name: edutainmentforge
        image: "edutainmentforge.azurecr.io/edutainmentforge:latest"
        env:
          - name: PORT
            value: "5000"
          - name: TTS_PROVIDER
            value: "azure"
          - name: AZURE_SPEECH_KEY
            secretRef: azure-speech-key
          - name: AZURE_SPEECH_REGION
            value: "eastus2"
          - name: AZURE_OPENAI_ENDPOINT
            secretRef: azure-openai-endpoint
          - name: AZURE_OPENAI_API_KEY
            secretRef: azure-openai-api-key
          - name: AZURE_OPENAI_API_VERSION
            value: "2024-02-15-preview"
          - name: AZURE_OPENAI_DEPLOYMENT_NAME
            value: "gpt-4o-mini"
          - name: AZURE_OPENAI_GPT4_DEPLOYMENT_NAME
            value: "gpt-4o"
          - name: USE_PREMIUM_AI
            value: "true"
          - name: USE_AI_ENHANCEMENT
            value: "true"
          - name: USE_PREMIUM_VOICES
            value: "true"
          - name: USE_VOICE_STYLES
            value: "true"
          - name: ENABLE_DYNAMIC_SSML
            value: "true"
          - name: LOG_LEVEL
            value: "INFO"
          - name: FLASK_ENV
            value: "production"
          - name: SARAH_VOICE
            secretRef: sarah-voice
          - name: MIKE_VOICE
            secretRef: mike-voice
          - name: AZURE_AD_TENANT_ID
            secretRef: azure-ad-tenant-id
          - name: AZURE_AD_CLIENT_ID
            secretRef: azure-ad-client-id
          - name: AZURE_AD_CLIENT_SECRET
            secretRef: azure-ad-client-secret
          - name: FLASK_SECRET_KEY
            secretRef: flask-secret-key
        resources:
          cpu: 1.0
          memory: 2.0Gi
        probes:
          - type: Liveness
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          - type: Readiness
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
    scale:
      minReplicas: 1
      maxReplicas: 10
      rules:
        - name: http-rule
          http:
            metadata:
              concurrentRequests: "5"
tags:
  environment: production
  application: edutainmentforge
